
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface A4_104232327_Symbol {
  /* terminals */
  public static final int INLINECOMMENTS = 21;
  public static final int PLUS = 7;
  public static final int INT = 4;
  public static final int EQUAL = 15;
  public static final int QUOTES = 19;
  public static final int SEMI = 9;
  public static final int RBRA = 14;
  public static final int RETURN = 5;
  public static final int GREATER = 24;
  public static final int IF = 25;
  public static final int LBRA = 13;
  public static final int PRINTF = 16;
  public static final int COMMENTS = 20;
  public static final int ID = 18;
  public static final int HASH = 17;
  public static final int COMMA = 10;
  public static final int MULT = 22;
  public static final int EOF = 0;
  public static final int NUMBER = 2;
  public static final int MAIN = 6;
  public static final int MINUS = 8;
  public static final int error = 1;
  public static final int RPAR = 12;
  public static final int FOR = 26;
  public static final int VOID = 3;
  public static final int LPAR = 11;
  public static final int LESS = 23;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "NUMBER",
  "VOID",
  "INT",
  "RETURN",
  "MAIN",
  "PLUS",
  "MINUS",
  "SEMI",
  "COMMA",
  "LPAR",
  "RPAR",
  "LBRA",
  "RBRA",
  "EQUAL",
  "PRINTF",
  "HASH",
  "ID",
  "QUOTES",
  "COMMENTS",
  "INLINECOMMENTS",
  "MULT",
  "LESS",
  "GREATER",
  "IF",
  "FOR"
  };
}

