
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface A5_104232327_Symbol {
  /* terminals */
  public static final int PLUSPLUS = 27;
  public static final int MULT = 23;
  public static final int LBRA = 13;
  public static final int COMMENTS = 20;
  public static final int CASE = 33;
  public static final int HASH = 17;
  public static final int SEMI = 9;
  public static final int INT = 4;
  public static final int FOR = 26;
  public static final int MINUS = 8;
  public static final int LTHAN = 25;
  public static final int RPAR = 12;
  public static final int COMMA = 10;
  public static final int PLUS = 7;
  public static final int MAIN = 6;
  public static final int IF = 28;
  public static final int INLINECOMMENTS = 21;
  public static final int ID = 18;
  public static final int EOF = 0;
  public static final int RETURN = 5;
  public static final int EQUAL = 15;
  public static final int error = 1;
  public static final int RBRA = 14;
  public static final int NUMBER = 2;
  public static final int VOID = 3;
  public static final int PRINTF = 16;
  public static final int SWITCH = 34;
  public static final int GTHAN = 24;
  public static final int COLON = 32;
  public static final int ELSE = 29;
  public static final int WHILE = 30;
  public static final int RETURNBOI = 36;
  public static final int DEFAULT = 35;
  public static final int LPAR = 11;
  public static final int QUOTES = 19;
  public static final int QString = 22;
  public static final int DO = 31;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "NUMBER",
  "VOID",
  "INT",
  "RETURN",
  "MAIN",
  "PLUS",
  "MINUS",
  "SEMI",
  "COMMA",
  "LPAR",
  "RPAR",
  "LBRA",
  "RBRA",
  "EQUAL",
  "PRINTF",
  "HASH",
  "ID",
  "QUOTES",
  "COMMENTS",
  "INLINECOMMENTS",
  "QString",
  "MULT",
  "GTHAN",
  "LTHAN",
  "FOR",
  "PLUSPLUS",
  "IF",
  "ELSE",
  "WHILE",
  "DO",
  "COLON",
  "CASE",
  "SWITCH",
  "DEFAULT",
  "RETURNBOI"
  };
}

